Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/TrailingWhitespace:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
